---

stages:
  - lint
  - test

bash:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck --shell=bash update.bash tests/setup

.script: &script
  stage: test
  script:
    - make tests

archlinux:
  image: archlinux/base
  before_script:
    - pacman -Syu --noconfirm --noprogressbar make grep pass git
  <<: *script

ubuntu:
  image: ubuntu
  before_script:
    - apt-get update -q && apt-get install -y make pass grep git
  <<: *script

debian:
  image: debian
  before_script:
    - apt-get update -q && apt-get install -y make pass grep wget git xz-utils
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
    - tar -xf password-store-1.7.3.tar.xz
    - make --directory=password-store-1.7.3 install
  <<: *script

fedora:
  image: fedora
  before_script:
    - dnf -y install make gpg pass grep git --setopt=install_weak_deps=False
  <<: *script

centos:
  image: centos
  before_script:
    - yum -y update && yum -y install make gpg grep wget git
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
    - tar -xf password-store-1.7.3.tar.xz
    - make --directory=password-store-1.7.3 install
  <<: *script

opensuse:
  image: opensuse
  before_script:
    - zypper -n refresh && zypper -n install make grep wget tar git
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
    - tar -xf password-store-1.7.3.tar.xz
    - make --directory=password-store-1.7.3 install
  <<: *script
